name: Continuous integration code quality checks

on: [ push ]

jobs:
  phpcs_check:
    name: PHPCS check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@afefcaf556d98dc7896cca380e181decb609ca44 # v2.10.0
        with:
          php-version: '7.4'
          coverage: none
          tools: composer, cs2pr

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check coding standards using PHPCS
        run: vendor/bin/phpcs -q --report=checkstyle | cs2pr
